p8105_hw1_yd2739
================
Yuxuan Du
2023-09-14

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

``` r
library("moderndive")
data("early_january_weather")
variables = colnames(early_january_weather)
observation_num = nrow(early_january_weather)
variable_num = ncol(early_january_weather)
mean_temp = mean(early_january_weather$temp)
q1_scatter = ggplot(data = early_january_weather, 
       mapping = aes(x = time_hour, 
                y = temp, 
                color = humid)) + 
  geom_point()
ggsave(
  'problem_1_scatter.png',
  plot = q1_scatter,
  device = png
)
```

    ## Saving 7 x 5 in image

``` r
q1_scatter
```

![](p8105_hw1_yd2739_files/figure-gfm/unnamed-chunk-2-1.png)<!-- --> the
variables in the dataset are: origin, year, month, day, hour, temp,
dewp, humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib,
time_hour.

the size of the data is 358 x 15.

the mean temperature is 39.5821229 degree.

## Problem 2

``` r
Q2_df = tibble(
  samp_10_norm = rnorm(10),
  samp_10_norm_logic = samp_10_norm > 0,
  samp_char_vec = c('A', 'B', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K'),
  samp_fac_vec = factor(c(-1, -1, 0, 0, 0, 0, 1, 1, 1, -1))
)
Q2_df
```

    ## # A tibble: 10 × 4
    ##    samp_10_norm samp_10_norm_logic samp_char_vec samp_fac_vec
    ##           <dbl> <lgl>              <chr>         <fct>       
    ##  1       0.728  TRUE               A             -1          
    ##  2       2.08   TRUE               B             -1          
    ##  3      -0.357  FALSE              D             0           
    ##  4       0.136  TRUE               E             0           
    ##  5      -0.0532 FALSE              F             0           
    ##  6       0.549  TRUE               G             0           
    ##  7      -1.20   FALSE              H             1           
    ##  8       0.496  TRUE               I             1           
    ##  9       0.0219 TRUE               J             1           
    ## 10      -0.865  FALSE              K             -1

``` r
mean(pull(Q2_df, samp_10_norm))
```

    ## [1] 0.1537819

``` r
mean(pull(Q2_df, samp_10_norm_logic))
```

    ## [1] 0.6

``` r
mean(pull(Q2_df, samp_char_vec))
```

    ## Warning in mean.default(pull(Q2_df, samp_char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(Q2_df, samp_fac_vec))
```

    ## Warning in mean.default(pull(Q2_df, samp_fac_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

among the four vector, char vector and factor vector cannot take mean

``` r
as.numeric(pull(Q2_df, samp_10_norm_logic))
as.numeric(pull(Q2_df, samp_char_vec))
as.numeric(pull(Q2_df, samp_fac_vec))
```

It says NAs introduced by coercion when executing char vec, which means
it cannot be transformed to numeric vector. But for factor vector it
seems transformed successfully to numeric vector but still cannot
calculate the mean
